### ISSUE TITLE
Sanic-restplus is not avilable on pypi

### ISSUE THREAD

**Issue by manuelsotoma** [ashleysommer/sanic-restplus#2]
> pip install sanic-restplus
Collecting sanic-restplus
  Could not find a version that satisfies the requirement sanic-restplus (from versions: )
No matching distribution found for sanic-restplus

**Comment by asyncee** [comment]
Will it ever be?

**Comment by ashleysommer** [comment]
Yes, I intend to release Sanic-restplus on pypi when it is finished being ported from Flask to Sanic.

However in its current state I believe it is not yet ready to be submitted to pypi.

There are still references to modules from Flask and Werkzeug in the code, which I need to remove and provide workaround functionality. Also in its current state it will crash, a lot.

I will edit the Readme to clarify that Sanic-restplus is still in the process of being ported.

**Comment by goranvrbaski** [comment]
> Yes, I intend to release Sanic-restplus on pypi when it is finished being ported from Flask to Sanic.

Do you need help with doing this?

**Comment by tomwojcik** [comment]
Welp, is it dead?

**Comment by ashleysommer** [comment]
@goranvrbaski
Yes, if others would like to contribute, that would be greatly appreciated. It is a big job for one person.

@tomwojcik
Nope, absolutely not dead.
Check the commits history, it has had regular updates. It got re-based on newer Flask-Restplus, then I added Sanic-Plugins-Framework compatibility, and recently it got Sanic 0.7.0 compatibility.

I use Sanic-Restplus for several Sanic projects at work, it is a useful tool.

It is not released on Pypi yet because theres too much untested code and lots of codepaths that I haven't explored yet. There are still references to Flask and Werkzeug in the code too.

**Comment by ashleysommer** [comment]
Sanic-Restplus is now released on pypi as of version 0.3.3.
